version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  deploy-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  deploy-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  deploy-bank-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  deploy-production:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy-dev
      - approve-test:
          type: approval
          requires:
           - deploy-dev
      - deploy-test:
          requires:
           - approve-test
      - approve-bank-test:
          type: approval
          requires:
           - deploy-test
      - deploy-bank-test:
          requires:
           - approve-bank-test
      - approve-production:
          type: approval
          requires:
           - deploy-bank-test
      - deploy-production:
          requires:
           - approve-production









